version: '3.5'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=schelly
      - POSTGRES_PASSWORD=postgres

  schelly-postgres-repo:
    image: tiagostutz/schelly-postgres
    build: .
    ports:
      - 7070:7070
    environment:
      - LOG_LEVEL=debug
      - BACKUP_FILE_PATH=/var/backups
      - DATABASE_NAME=schelly
      - DATABASE_CONNECTION_HOST=db
      - DATABASE_CONNECTION_PORT=5432
      - DATABASE_AUTH_USERNAME=postgres
      - DATABASE_AUTH_PASSWORD=postgres

networks:
  default:
    name: schelly-postgres-net